### ISSUE TITLE
"The following plugin is incompatible with the current KeePass version"

### ISSUE THREAD

**Issue by unalignedcoder** [smorks/keepassnatmsg#10]
Keepass 2.3.7 On windows 7 SP1
.NET Framework 4.7.1

What's not working?

![2018-03-05 12_55_20-keepass](https://user-images.githubusercontent.com/16850566/36961268-be8724bc-2074-11e8-83a3-f2d7fcb13bcf.jpg)

**Comment by smorks** [comment]
i'm assuming you're running beta8? i think if you try beta 7, it should work. let me know if it does.

i [added a fix](https://github.com/smorks/keepassnatmsg/commit/8033170b3950482691af9220220d6d863daad72f) in beta 8 to use TLS 1.2 to check the github website for updates, since [github doesn't support TLS 1.0 & 1.1 anymore](https://githubengineering.com/crypto-deprecation-notice/). i believe it depends on certain updates being installed in Windows (see [here](https://support.microsoft.com/en-ca/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) and [here](https://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/)). i'm guessing that's what's causing the error (although it's working fine for me in Windows 7 & 10).

Anyways, i'll see if there's a better way, or maybe just better handle when checking for updates fails.

**Comment by unalignedcoder** [comment]
Yes it was beta 8, I've tried with beta 7 on my laptop at home which has the same configuration (windows 7 framework 4.7.1, keepass 2.3.7) and unfortunately it gives the same error message.

**Comment by smorks** [comment]
hmm i'll do some testing and see if i can find the issue. thanks.

**Comment by unalignedcoder** [comment]
Still it's strange that Keepass won't even load the plugin. Maybe it's a problem with this version of Keepass?

**Comment by smorks** [comment]
yeah i just tested with KeePass 2.37 and i got the same error. it appears to work with 2.38. strange.

**Comment by unalignedcoder** [comment]
Oh, Keepass 2.3.8 is out? Will try that then ))

**Comment by unalignedcoder** [comment]
Uhm, I've got a different error message when trying to install the messaging host...

![2018-03-05 22_31_23-proxy download error](https://user-images.githubusercontent.com/16850566/36986805-f78f6242-20c4-11e8-963f-81a449dad4f3.jpg)

**Comment by smorks** [comment]
is that using beta 7 or 8?

**Comment by unalignedcoder** [comment]
beta 7

**Comment by smorks** [comment]
try beta 8, if you haven't already.

**Comment by unalignedcoder** [comment]
No dice, same error when clicking on "Install Native messaging host".

**Comment by smorks** [comment]
hmmm, i'll look into it...

**Comment by smorks** [comment]
can you double-check in your "Installed Updates" in "Add/Remove Programs" that KB3140245 is installed?

![screenshot_1](https://user-images.githubusercontent.com/1030007/36989640-e8061be8-2067-11e8-8c71-a9dfcc0705a7.png)

**Comment by smorks** [comment]
@unalignedcoder are you still experiencing thing issue?

**Comment by smorks** [comment]
closing for now, haven't heard back on this.
