### ISSUE TITLE
KeepassXC-browser needs manually pressing reload to work and keepassnatmsg crashes when Keepass is being closed.

### ISSUE THREAD

**Issue by Mcinwwl** [smorks/keepassnatmsg#23]
To start from have quite unusual Setup - Windows 7 pro with Firefox, but in Windows, I have 2 accounts (Admin and user), but FF profile is installed in the location accessible for both, so I have one KeepassXC-browser instance used in two Accounts.

Some time ago I installed KeepassXC-browser and KeepassNatMsg plug-in. I opened both in Admin account, checked KeepassNatMsg options, and pressed "Install/Update Native Messaging Host". It worked and browser-application connection was automatic.

Then I re-logged to user account. Connection was not automatic so I pressed reload - not working.
I entered the options KeepassNatMsg options from user account and pressed "Install/Update Native Messaging Host". It got installed and remains like that. 

However, there are two issues:
Browser extension does not recognize that Keepass is running - I have to press reload to make it work.
When I close Keepass, I receive error message like the one below:
"Program keepassnatmsg-proxy has stopped to work"

Details screen shows this:
```
Podpis problemu:
  Nazwa zdarzenia problemu:	CLR20r3
  Podpis problemu: 01:	keepassnatmsg-proxy.exe
  Podpis problemu: 02:	0.0.6.36827
  Podpis problemu: 03:	5b7cbc06
  Podpis problemu: 04:	System.Core
  Podpis problemu: 05:	4.7.3221.0
  Podpis problemu: 06:	5b885a82
  Podpis problemu: 07:	533
  Podpis problemu: 08:	61
  Podpis problemu: 09:	System.IO.IOException
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.48
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	35ac
  Dodatkowe informacje 2:	35acd98331d5de5a95eef5c6b00f8ca5
  Dodatkowe informacje 3:	291d
  Dodatkowe informacje 4:	291d5960c7b5535e8443bace076f326f
```
These issues are not deadly, as the program itself works, but I'd be glad if these are fixable :)

System: Windows 7 x64 professional PL
Browser: Firefox x64 current branch (currently 64.0.2)
Keepass: Keepass 2.40
KeepassXC-browser - current (1.3.2)
KeepassNatMsg - 2.0.3

**Comment by Mcinwwl** [comment]
Thanks! For me it's 100% repro (both Admin and User account) So I can provide more logs if there's a way to do so.

**Comment by Mcinwwl** [comment]
No. First of all, it happens when I use only one account at the time, and I always shut down PC when finishing, so little chances of mistake.
Second, I run Firefox via shortcut with -noremote switch, so even if i tried, it will not let me open two session with the same account.
Default Firefox profile is not connected with Keepass and has no plugins installed.

**Comment by smorks** [comment]
i will try and mimic your environment to see if i can duplicate the problem. i'll let you know if i have any further questions.

**Comment by smorks** [comment]
sorry for taking so long to get back to you - so i had a Win7 machine with two different account - "Admin" and "User". I created a new Firefox profile for Admin, put it in a location where both users had access, then logged in as User, and pointed to the same Firefox profile. That appeared to work with no issues.

I then had to do the "Install/Update Native Messaging Host" in KeePassNatMsg for both users, which makes sense because it puts files in `%LOCALAPPDATA%`. Once that was done, I first connected in the keepassxc-browser extension in the Admin account, and it appeared to work. I then logged into the User account, opened Firefox, and it was connected as well without having to do anything (which makes sense, since the FF profile is shared).

I also tried with the -no-remote switch in Firefox, but everything seemed to be working fine for me too.

Does that sound like I got your environment right?

From the error you're getting, it almost sounds like the keepassnatmsg-proxy.exe is running when it shouldn't be. Are  you able to check in your Task Manager (make sure the Show Processes for All Users is checked) to see if you can see that process running, even when Firefox is closed? (it shouldn't be running if FF is closed)

Other than that, i'm not sure what else the problem might be?

**Comment by Mcinwwl** [comment]
Thanks for investigation, I'll check out. maybe it's an issue on my side?

> From the error you're getting, it almost sounds like the keepassnatmsg-proxy.exe is running when it shouldn't be. 

I checked and keepassnatmsg-proxy.exe process dies as soon as I quit Firefox.

**Comment by Mcinwwl** [comment]
Hm. I tested it on VM today.
Pure windows 7 home Premium x64 PL + all updates.
Newest Firefox installed.
Keepass, keepassnatmsg installed.
Pure new kdbx database.
Addon in Firefox installed.
Native messaging host for Firefox installed.
New connection created.

I established connection.
I closed Keepass.
I entered Facebook (any page with login fields will do).
"Program keepassnatmsg-proxy has stopped to work".
---

Then I closed Firefox
Opened Keepass.
Re-opened Firefox.
Went Facebook (any page with login fields will do).
Browser Addon-Keepass connection as not Established automatically. I had to press the KeePassXC-browser icon and press "reload".
---

Which sums up to the point, that there is nothing wrong with my double Admin-user account in Windows. Sorry for making you re-create my setup, I should have checked that earlier :/

But, from the other hand, bug is replicable in simpler environment.

The only change from default settings I made was disabling global hotkeys in Keepass, as they conflict with Polish keyboard layout.

> From the error you're getting, it almost sounds like the keepassnatmsg-proxy.exe is running when it shouldn't be.

Indeed, it does not die when I shut down KeePass, I had to perform any action in the browser using the KeePassXC-browser, which causes it to crash.

Opening website with login fields is such an action in this case.

**Comment by smorks** [comment]
i'll see if i can have the proxy better handle when keepass itself closes, but i'm not exactly sure how much control i have over that.

anyways, thanks for the thorough investigation you did. i'll see what i can do.

**Comment by gardian12** [comment]
Crash of keepassnatmsg-proxy on Win machine solved.
Pull request is outstanding.

**Comment by smorks** [comment]
this should be fixed now with the new `keepassnatmsg-proxy` release.
