### ISSUE TITLE
Can't Reopen database from extension

### ISSUE THREAD

**Issue by ykis-0-0** [smorks/keepassnatmsg#94]
Hi, this is a great plugin, everything runs smoothly but I've met a small problem:

**Environment**:
Here's what I'm using:
OS: Windows 10 Pro x64
KeePass: v2.50
KeePassNatMsg: v2.0.14.0 *(.plgx)*
Proxy: 0.0.9.28122
Browser: Chrome100.0.4896.127
Extension: KeePassXC-Browser v1.7.12

**Situation**
When the database is locked, I can't trigger the unlock prompt by clicking the Unlock button in the extension "bubble".

Thanks for you great plugin! If you need more info for this please tell me.

**Comment by smorks** [comment]
yeah, i'm seeing this too, but it looks like it does try and bring KeePass to the foreground because the icon does flash in my taskbar, but i still get this message in the extension, so something doesn't appear to be working quite right:

![Capture](https://user-images.githubusercontent.com/1030007/165429561-ab54cbd0-4467-47e9-b36c-e57cef7550b3.PNG)

i'll investigate more.

**Comment by ykis-0-0** [comment]
I've just tried again, but my situation is the taskbar icon doesn't flash, si I guess for me KeePass doesn't even try to activate itself

**Comment by ykis-0-0** [comment]
Hi @smorks, sorry if this disturbed you, but the problem still exists, and manually unlocking KeePass to get autofill isn't a great workflow🤧.

What would be the code that tells KeePass to prompt for unlocking the database? I may be capable to help if you don't mind 😃

**Comment by ykis-0-0** [comment]
Hi, just to update that KeePassXC-Browser can activate the unlock prompt again, so I think closing this issue would be better 😁
